package com.rany.uic.dao.mapper;

import com.rany.uic.dao.po.AccountPO;

public interface AccountPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Dec 27 21:15:53 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Dec 27 21:15:53 CST 2022
     */
    int insert(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Dec 27 21:15:53 CST 2022
     */
    int insertSelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Dec 27 21:15:53 CST 2022
     */
    AccountPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Dec 27 21:15:53 CST 2022
     */
    int updateByPrimaryKeySelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Dec 27 21:15:53 CST 2022
     */
    int updateByPrimaryKey(AccountPO record);
}