package com.rany.uic.infra.mapper;

import com.rany.uic.infra.po.SafeStrategyPO;

public interface SafeStrategyPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Aug 17 23:37:07 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Aug 17 23:37:07 CST 2023
     */
    int insert(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Aug 17 23:37:07 CST 2023
     */
    int insertSelective(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Aug 17 23:37:07 CST 2023
     */
    SafeStrategyPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Aug 17 23:37:07 CST 2023
     */
    int updateByPrimaryKeySelective(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Aug 17 23:37:07 CST 2023
     */
    int updateByPrimaryKey(SafeStrategyPO record);
}