package com.rany.uic.dao.po;

import java.util.Date;

public class IsvPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.id
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.name
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.url
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.short_name
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.country
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.status
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.is_deleted
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.register_ip
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.phone
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.email
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.create_by
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.update_by
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.gmt_create
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.gmt_modified
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.max_tenants
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    private Integer maxTenants;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.id
     *
     * @return the value of isv.id
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.id
     *
     * @param id the value for isv.id
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.name
     *
     * @return the value of isv.name
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.name
     *
     * @param name the value for isv.name
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.url
     *
     * @return the value of isv.url
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.url
     *
     * @param url the value for isv.url
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.short_name
     *
     * @return the value of isv.short_name
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.short_name
     *
     * @param shortName the value for isv.short_name
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.country
     *
     * @return the value of isv.country
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.country
     *
     * @param country the value for isv.country
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.status
     *
     * @return the value of isv.status
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.status
     *
     * @param status the value for isv.status
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.is_deleted
     *
     * @return the value of isv.is_deleted
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.is_deleted
     *
     * @param isDeleted the value for isv.is_deleted
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.register_ip
     *
     * @return the value of isv.register_ip
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.register_ip
     *
     * @param registerIp the value for isv.register_ip
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.phone
     *
     * @return the value of isv.phone
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.phone
     *
     * @param phone the value for isv.phone
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.email
     *
     * @return the value of isv.email
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.email
     *
     * @param email the value for isv.email
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.create_by
     *
     * @return the value of isv.create_by
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.create_by
     *
     * @param createBy the value for isv.create_by
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.update_by
     *
     * @return the value of isv.update_by
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.update_by
     *
     * @param updateBy the value for isv.update_by
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.gmt_create
     *
     * @return the value of isv.gmt_create
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.gmt_create
     *
     * @param gmtCreate the value for isv.gmt_create
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.gmt_modified
     *
     * @return the value of isv.gmt_modified
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.gmt_modified
     *
     * @param gmtModified the value for isv.gmt_modified
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.max_tenants
     *
     * @return the value of isv.max_tenants
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public Integer getMaxTenants() {
        return maxTenants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.max_tenants
     *
     * @param maxTenants the value for isv.max_tenants
     *
     * @mbggenerated Thu Jan 05 22:18:51 CST 2023
     */
    public void setMaxTenants(Integer maxTenants) {
        this.maxTenants = maxTenants;
    }
}