package com.rany.uic.domain.dao.mapper;

import com.rany.uic.domain.po.AccountPO;

public interface AccountPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int insert(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int insertSelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    AccountPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int updateByPrimaryKeySelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int updateByPrimaryKey(AccountPO record);
}