package com.rany.uic.domain.dao.mapper;

import com.rany.uic.domain.po.SafeStrategyPO;

public interface SafeStrategyPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int insert(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int insertSelective(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    SafeStrategyPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int updateByPrimaryKeySelective(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Thu Jan 05 23:59:38 CST 2023
     */
    int updateByPrimaryKey(SafeStrategyPO record);
}